Low: zabbixserver: reduce unimportant or incorrect error logs.
In case of the stop op the following "ERROR" is not error because
the process is alredy killed by RA.
ERROR: /usr/lib/ocf/lib/heartbeat/ocf-shellfuncs: line 434: kill: (XXX) - No such process
In other cases this ERROR may be truely an error, but it can be noticed by othe messages.